import React from 'react';
import { AlertCircle, CheckCircle, Clock } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '../../components/ui/tooltip';
import { format } from 'date-fns';

interface PlanGenerationBadgeProps {
  isAutoGenerated: boolean;
  autoGeneratedAt?: Date | null;
  generatedDate?: string | null;
}

const PlanGenerationBadge: React.FC<PlanGenerationBadgeProps> = ({ 
  isAutoGenerated, 
  autoGeneratedAt, 
  generatedDate 
}) => {
  if (!isAutoGenerated) return null;
  
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300">
            <CheckCircle className="w-3 h-3 mr-1" />
            Auto-generated
          </div>
        </TooltipTrigger>
        <TooltipContent>
          <div className="text-sm">
            <p className="font-semibold">AI Auto-generated Plans</p>
            {autoGeneratedAt && (
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Generated on: {format(new Date(autoGeneratedAt), 'PPP')}
              </p>
            )}
            {generatedDate && (
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Plans for: {format(new Date(generatedDate), 'PPP')}
              </p>
            )}
          </div>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};

export default PlanGenerationBadge; 